ci

diff --git a/.github/workflows/android-test.yml b/.github/workflows/android-test.yml
--- a/.github/workflows/android-test.yml
+++ b/.github/workflows/android-test.yml
@@ -107,21 +107,22 @@ jobs:
           disk-size: 2G
           heap-size: 1G
           disable-animations: true
-          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot-save -noaudio -no-boot-anim -camera-back none
+          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot-save -no-audio -no-boot-anim -camera-back none
           script: |
             chmod +x $GITHUB_WORKSPACE/appium/gradlew
-            $GITHUB_WORKSPACE/appium/gradlew -p $GITHUB_WORKSPACE/appium clean test -DappPath=$GITHUB_WORKSPACE/build/app/outputs/flutter-apk/app-pro-release.apk && TEST_EXIT_CODE=0 || TEST_EXIT_CODE=$?
             
-            echo "Test execution finished. Exit code: ${TEST_EXIT_CODE:-0}"
-
-            echo "Capturing Logcat..."
+            echo "Starting Appium test..."
+            $GITHUB_WORKSPACE/appium/gradlew -p $GITHUB_WORKSPACE/appium clean test -DappPath=$GITHUB_WORKSPACE/build/app/outputs/flutter-apk/app-pro-release.apk && TEST_RESULT=0 || TEST_RESULT=1
+            
+            echo "Tests completed with code: $TEST_RESULT"
+            
+            echo "Saving Logcat..."
             /usr/local/lib/android/sdk/platform-tools/adb logcat -d > $GITHUB_WORKSPACE/logcat.txt
-
-            if [ "$TEST_EXIT_CODE" -ne 0 ]; then
-              echo "Tests failed. Exiting with error code."
-              exit $TEST_EXIT_CODE
+            
+            if [ $TEST_RESULT -ne 0 ]; then
+              echo "The tests failed."
+              exit 1
             fi
-
       - name: Upload Test Reports
         if: always()
         uses: actions/upload-artifact@v4
